import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Local Python AI runtime and generated bytecode.
    "ai-service/.venv/**",
    "ai-service/**/__pycache__/**",
    // Generated third-party runtime vendored for local-only worker loading.
    "public/detector-assets/opencv.js",
  ]),
]);

export default eslintConfig;
